# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d82ab4435d1ba792c23f93ec47bd0bbddcb29dacd3b2c3f07e22b7d67c9d7f421eac0787b711c3a3cc2d363801f8422d66d08e16c77d70bc913f2ca117a64461

test:
  secret_key_base: 001d401f80b1f566ce9a093b06c17b16e488acbb0cc8c1ce0b6705e0a729d64eb0129502283c82ea77630ab54b2ac0e9bebced5c872cad1d4422e0923e085746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
